#ifndef __Boids3DFrame__
#define __Boids3DFrame__

/**
@file
Subclass of Frame, which is generated by wxFormBuilder.
*/

#include "BoidsUI.h"

//// end generated include

/** Implementing Frame */
class Boids3DFrame : public Frame
{
	protected:
		// Handlers for Frame events.
		void NumberOfBoidsChanged( wxCommandEvent& event );
		void viewDistanceChanged( wxCommandEvent& event );
		void SimulationSpeedChanged( wxCommandEvent& event );
	public:
		/** Constructor */
		Boids3DFrame( wxWindow* parent );
	//// end generated class members
		wxWindow *Get3DPanel() { return m_boidsPanel; }


};

#endif // __Boids3DFrame__
