#ifndef __Boids3DFrame__
#define __Boids3DFrame__

/**
@file
Subclass of Frame, which is generated by wxFormBuilder.
*/

#include "BoidsUI.h"

//// end generated include

#include "world.hpp"

/** Implementing Frame */
class Boids3DFrame : public Frame
{
	protected:
		// Handlers for Frame events.
		void BoidsChanged( wxCommandEvent& event );
		void SpeedChanged( wxCommandEvent& event );
		void WorldSizeChanged( wxCommandEvent& event );
		void ViewDistanceChanged( wxCommandEvent& event );
		void ViewAngleChanged( wxCommandEvent& event );
		void AlignmentChanged( wxCommandEvent& event );
		void CohesionChanged( wxCommandEvent& event );
		void SeparationChanged( wxCommandEvent& event );
	public:
		/** Constructor */
		Boids3DFrame( wxWindow* parent );
	//// end generated class members
		wxWindow *Get3DPanel() { return m_boidsPanel; }

		std::string GetBoids() { return std::string(m_boidsText->GetValue()); }
		void SetBoids(wxString value) { m_boidsText->SetValue(value); }

		std::string GetSpeed() { return std::string(m_speedText->GetValue()); }
		void SetSpeed(wxString value) { m_speedText->SetValue(value); }

		std::string GetWorldSize() { return std::string(m_worldSizeText->GetValue()); }
		void SetWorldSize(wxString value) { m_worldSizeText->SetValue(value); }

		std::string GetViewDistance() {return std::string(m_viewDistanceText->GetValue()); }
		void SetViewDistance(wxString value) { m_viewDistanceText->SetValue(value); }

		std::string GetViewAngle() { return std::string(m_viewAngleText->GetValue()); }
		void SetViewAngle(wxString value) { m_viewAngleText->SetValue(value); }

		std::string GetAlignment() { return std::string(m_alignmentText->GetValue()); }
		void SetAlignment(wxString value) { m_alignmentText->SetValue(value); }

		std::string GetCohesion() { return std::string(m_cohesionText->GetValue()); }
		void SetCohesion(wxString value) { m_cohesionText->SetValue(value); }

		std::string GetSeparation() { return std::string(m_separationText->GetValue()); }
		void SetSeparation(wxString value) { m_separationText->SetValue(value); }

		void SetWorld( World<float>* world) { world_ = world; }
	private:
		World<float>* world_;
};

#endif // __Boids3DFrame__
